### ISSUE TITLE
Uncaught DOMException: Failed to execute 'drawImage' on 'OffscreenCanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state at OffscreenCanvasRenderingContext2D.drawImage

### ISSUE THREAD

**Issue by Suvanth-Erranki** [maitian352/Meadow-Guarder#248]
![image](https://user-images.githubusercontent.com/76885647/148656355-94fc6610-0a38-498c-a110-2e3cce996d21.png)
![image](https://user-images.githubusercontent.com/76885647/148656416-7fa09895-4ea7-4f97-bdb6-c672cefdd6cc.png)
![image](https://user-images.githubusercontent.com/76885647/148656457-9724e25c-c379-431c-bf35-54722c6adedf.png)
![image](https://user-images.githubusercontent.com/76885647/148656479-a335a3c9-ca6b-48ba-93af-792377ea8afb.png)
![image](https://user-images.githubusercontent.com/76885647/148656487-b43920b4-69ee-4e5d-8b4b-43bc810c7e6f.png)
![image](https://user-images.githubusercontent.com/76885647/148656498-09b32456-c0c4-4fce-8ba3-bd0d051192ed.png)
![image](https://user-images.githubusercontent.com/76885647/148656513-6618ff71-d4e5-4d95-9fed-90daf5dff24c.png)
![image](https://user-images.githubusercontent.com/76885647/148656523-f12ef3e6-8a9b-405b-9e1c-dfa0e04c77d2.png)

I went idle and left the tab open while I was on another tab. Eventually, I came back and found that I was dead (because of monsters), but when I tried to respawn, the screen would be frozen.

![image](https://user-images.githubusercontent.com/76885647/148656396-85537ada-fe5e-4244-902d-dbaad56ec693.png)

I can provide a video if necessary.

**Comment by maitian352** [comment]
The images unloaded i think.

**Comment by Suvanth-Erranki** [comment]
> The images unloaded i think.

I just updated the issue with much more images.

**Comment by Suvanth-Erranki** [comment]
Also, I ran the command `for(var i in Monster.list){console.log(Monster.list[i].monsterType)}`.
![image](https://user-images.githubusercontent.com/76885647/148656611-8d7c35b2-6a49-4c5d-84f0-d1d82363008b.png)

**Comment by Suvanth-Erranki** [comment]
I also ran `console.log(Img)`.
![image](https://user-images.githubusercontent.com/76885647/148656655-1ed06b9f-5500-4786-8e39-b3f8f96311e9.png)

**Comment by Suvanth-Erranki** [comment]
And I ran `console.log(Img["GasMask_1 Red"].src)`. I got this:
![image](https://user-images.githubusercontent.com/76885647/148656714-2815b4d2-a6ef-4a69-bf4d-a26e1b9da188.png)

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/148656747-87ff049d-fc7e-43e3-97fb-82028fd4540c.png)

This probably won't get fixed unless a breakthrough is made.

**Comment by maitian352** [comment]
Fixed.

**Comment by Suvanth-Erranki** [comment]
![image](https://user-images.githubusercontent.com/76885647/150878823-d03046ae-7b91-4310-89ff-e5bd2d2b1cf2.png)
![image](https://user-images.githubusercontent.com/76885647/150878835-eeb59b23-0b4c-4567-ac86-140f91f1608c.png)

Chat Messages still show though.

![image](https://user-images.githubusercontent.com/76885647/150878901-fa2da189-3f4a-4984-bfea-51b3b3c509ca.png)

**Comment by Suvanth-Erranki** [comment]
You can't fix this.
